################################################################################
# Copyright (c) 2020 ContinualAI Research                                      #
# Copyrights licensed under the CC BY 4.0 License.                             #
# See the accompanying LICENSE file for terms.                                 #
#                                                                              #
# Date: 1-05-2020                                                              #
# Author(s): Vincenzo Lomonaco                                                 #
# E-mail: contact@continualai.org                                              #
# Website: clair.continualai.org                                               #
################################################################################

name: avalanche-env
channels:
- pytorch
- conda-forge
dependencies:
- psutil
- python>=3.6,<3.9
- pytorch::pytorch
- pytorch::torchvision
- tensorboard
- scikit-learn
- matplotlib
- numpy
- conda-forge::quadprog
- tqdm
- pip
- pip:
    - pytorchcv
    - googledrivedownloader
