################################################################################
# Copyright (c) 2020 ContinualAI Research                                      #
# Copyrights licensed under the CC BY 4.0 License.                             #
# See the accompanying LICENSE file for terms.                                 #
#                                                                              #
# Date: 1-05-2020                                                              #
# Author(s): Vincenzo Lomonaco                                                 #
# E-mail: contact@continualai.org                                              #
# Website: clair.continualai.org                                               #
################################################################################

channels:
- conda-forge
dependencies:
- psutil
- tensorboard
- scikit-learn
- matplotlib
- numpy
- conda-forge::quadprog
- tqdm
- pip
- conda-forge::pycodestyle
- sphinx
- sphinx_rtd_theme
- conda-forge::astroid=2.4.2
- conda-forge::sphinx-autoapi
- pip:
    - pytorchcv
    - googledrivedownloader
