name: docstring coverage

on: [push, pull_request]

jobs:
  build:
    name: docstring coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: JackMcKew/python-interrogate-check@main
        with:
          path: 'avalanche'
          fail-under: 1
          # badge-location: 'badges/interrogate_badge.svg'