################################################################################
# Copyright (c) 2021 ContinualAI.                                              #
# Copyrights licensed under the MIT License.                                   #
# See the accompanying LICENSE file for terms.                                 #
#                                                                              #
# Date: 28-01-2021                                                             #
# Author(s): Gabriele Graffieti                                                #
# E-mail: contact@continualai.org                                              #
# Website: clair.continualai.org                                               #
################################################################################


name: docstring coverage

on:
  push:
    paths-ignore:
      - docs/gitbook/**
  pull_request:
    paths-ignore:
      - docs/gitbook/**

jobs:
  build:
    name: docstring coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: JackMcKew/python-interrogate-check@main
        with:
          path: 'avalanche'
          fail-under: 1
          # badge-location: 'badges/interrogate_badge.svg'