name: sphinx compilation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: build_sphinx_doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ammaraskar/sphinx-action@master
        with:
          pre-build-command: "sphinx-apidoc -f -d 4 -o docs/api/ avalanche/"
          build-command: "sphinx-build -b dirhtml docs/ doc_html/"
          docs-folder: "docs/"