################################################################################
# Copyright (c) 2021 ContinualAI.                                              #
# Copyrights licensed under the MIT License.                                   #
# See the accompanying LICENSE file for terms.                                 #
#                                                                              #
# Date: 14-03-2021                                                             #
# Author(s): Gabriele Graffieti                                                #
# E-mail: contact@continualai.org                                              #
# Website: avalanche.continualai.org                                           #
################################################################################


name: test coverage

on:
  push:
    paths-ignore:
      - docs/gitbook/**
  pull_request:
    paths-ignore:
      - docs/gitbook/**

jobs:
  build:
    name: test coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: avalanche-env
          python-version: 3.8
          auto-activate-base: false
      - name: install conda environment
        run: |
          conda install pytorch torchvision cpuonly -c pytorch -y
          conda env update --file environment.yml
      - name: install coverage.py and coverage-badge.py
        run: |
          pip install coverage
          pip install coverage-badge
      - name: Do unit test with coverage
        run: |
          FAST_TEST=True USE_GPU=False coverage run -m unittest
      - name: Produce report and badge
        run: |
          coverage report > coverage_report.txt
          coverage-badge -o coverage-badge.svg
      - name: clone reports repository
        # if: always() && github.event_name == 'push' && github.repository == 'ContinualAI/avalanche'
        uses: actions/checkout@v2
        with:
          repository: 'ContinualAI/avalanche-report'
          ref: main
          path: 'avalanche-reports'
          token: ${{ secrets.REPORT_TOKEN }}
      - name: commit report and badge
        # if: always() && github.event_name == 'push' && github.repository == 'ContinualAI/avalanche'
        run: |
          mv coverage-badge.svg avalanche-reports/badge/
          mv coverage_report.txt avalanche-reports/test_coverage/
          cd avalanche-reports
          git config --local user.email ${{ secrets.EMAIL }}
          git config --local user.name ${{ secrets.NAME }}
          git pull
          git add .
          git commit -m "Update coverage badge and report" -a || true
          git pull
      - name: Push changes
        # if: always() && github.event_name == 'push' && github.repository == 'ContinualAI/avalanche'
        continue-on-error: true
        uses: ad-m/github-push-action@master
        with:
          repository: ContinualAI/avalanche-report
          branch: main
          directory: avalanche-reports
          github_token: ${{ secrets.REPORT_TOKEN }}
